# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
extra-deps: 
    - HTTP-4000.2.23
    - mtl-2.2.1
    - network-2.6.3.1
    - network-uri-2.6.1.0
    - old-locale-1.0.0.7
    - old-time-1.1.0.3
    - parsec-3.1.11
    - random-1.1
    - stm-2.4.4.1
    - text-1.2.2.1
    - zlib-0.5.4.2
resolver: ghc-7.10.3
flags: {}
extra-package-dbs: []
packages: []
